[project]
name = "rpa"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
scripts = { awin-pyside6 = "pyside6_app:main" }
dependencies = [
    "beautifulsoup4>=4.14.2",
    "drissionpage>=4.1.1.2",
    "dulwich>=0.25.2",
    "html5lib>=1.1",
    "loguru>=0.7.3",
    "pandas>=2.3.3",
    "pyperclip>=1.11.0",
    "questionary>=2.0.1",
    "rich>=13.7.0",
    "textual>=3.0.0",
    "notify-py>=0.3.2",
    "platformdirs>=4.3.6",
    "pydantic>=2.11.5",
    "pyside6>=6.9.0",
    "pyinstaller>=6.20.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-qt>=4.4.0",
    "responses>=0.25.7",
]
